#!/usr/bin/env bash
if [ "$1" == "up" ]; then
	amixer set Master 5%+
elif [ "$1" == "down" ]; then
	amixer set Master 5%-
elif [ "$1" == "max" ]; then
	amixer set Master 100%
else
	echo "Needs args: up, down, or max"
fi
