#!/usr/bin/env bash
bspwm () {
	# Set wrokspaces
	bspc monitor $(bspc query -M --names | head -n 1) -d 1 2 3 4 5 6 7 8 9 10

	sh $SCRIPTS/new-monit-setup

	wallpaperinit -set
	bash $SCRIPTS/swap caps

	# Set wmname for pycharm and other things
	wmname LG3D
}

dwm () {
	sxhkd &
	compton &

	wallpaperinit -set
	bash $SCRIPTS/swap caps
}

sowm () {
	compton &
	dunst &
	xscreensaver &
	redshift -P -O 3500 &

	wallpaperinit -set
	bash $SCRIPTS/swap caps
}


if [ "$1" == "bspwm" ]; then
	bspwm
elif [ "$1" == "dwm" ]; then
	dwm
elif [ "$1" == "sowm" ]; then
	sowm
fi
